### ISSUE TITLE
[Test] Check that website clients connect to the vehicle WebSocket

### ISSUE THREAD

**Issue by BloodFutur** [BloodFutur/geicar#61]
## Description

The website is connecting to the vehicle using WebSocket. However, if we connect a computer to the local network of the vehicle (192.168.1.0), we do not know whether we can connect the websocket server and see ROS topic data.

## ToDo

- [x] Change the Javascript `ros.js` websocket address to 192.168.1.1
- [x] Connect the local network of the car
- [x] Try launching the script
- [x] Check whether it connects
   - [x] if it does not work we probably need to update firewall ports (using `ufw`)
- [x] Finally, add an input on the website so the user can choose the websocket server address.

**Comment by BloodFutur** [comment]
So we need the right websocket address, if we connect to the local network (Ethernet) or WiFi (eduroam). The IP address is different. We also need to make a HTTP server so that the vehicle gives an access to the website (that will use the websocket)
